name: Build and Release Extension
on:
  push:
    tags:
    - "*.*.*"
permissions:
  contents: write
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install Dependencies
      run: npm ci
    - name: Build Extension
      run: npm run build
    - name: Generate Archive 
      run: zip -r tplo-${{ github.ref_name }}.zip *
      working-directory: dist
    - name: Release Version
      uses: softprops/action-gh-release@v1
      with:
        files: dist/tplo-${{ github.ref_name }}.zip